from enum import Enum


class RequirementState(str, Enum):
    SATISFIED = "SATISFIED"
    UNSATISFIED = "UNSATISFIED"
    PENDING = "PENDING"
    CONFLICTED = "CONFLICTED"
    STALE = "STALE"
    OUT_OF_SCOPE = "OUT-OF-SCOPE"
    INAPPLICABLE = "INAPPLICABLE"
    INDETERMINATE = "INDETERMINATE"


class ConsensusState(str, Enum):
    ACHIEVED = "CONSENSUS-ACHIEVED"
    NOT_ACHIEVED = "CONSENSUS-NOT-ACHIEVED"
    CONFLICTED = "CONSENSUS-CONFLICTED"
    INDETERMINATE = "CONSENSUS-INDETERMINATE"


class AdmissibilityState(str, Enum):
    ADMIT = "ADMIT"
    BLOCK = "BLOCK"
    DEFER = "DEFER"
    REVALIDATE = "REVALIDATE"
    RECONSTRUCT = "RECONSTRUCT"


class AtomicityState(str, Enum):
    NO_EFFECT = "ATOMIC-NO-EFFECT"
    PARTIAL = "ATOMIC-PARTIAL"
    COMPLETE = "ATOMIC-COMPLETE"
    INDETERMINATE = "ATOMIC-INDETERMINATE"


class FinalityState(str, Enum):
    FINAL = "FINAL"
    NOT_FINAL = "NOT-FINAL"
    PENDING = "FINALITY-PENDING"
    CONFLICTED = "FINALITY-CONFLICTED"
    INDETERMINATE = "FINALITY-INDETERMINATE"
    REVALIDATION_REQUIRED = "FINALITY-REVALIDATION-REQUIRED"
    RECONSTRUCTION_REQUIRED = "FINALITY-RECONSTRUCTION-REQUIRED"


class ReconciliationState(str, Enum):
    RECONCILED = "RECONCILED"
    RECONCILED_WITH_RESIDUAL_CONFLICT = "RECONCILED-WITH-RESIDUAL-CONFLICT"
    REVALIDATION_REQUIRED = "REVALIDATION-REQUIRED"
    RECONSTRUCTION_REQUIRED = "RECONSTRUCTION-REQUIRED"
    UNRESOLVED = "UNRESOLVED"
    INDETERMINATE = "INDETERMINATE"


class ContinuityState(str, Enum):
    PRESERVED = "PRESERVED"
    DEGRADED = "DEGRADED"
    BROKEN = "BROKEN"
    RECONSTRUCTED = "RECONSTRUCTED"
    INDETERMINATE = "INDETERMINATE"
